export const modulesArr = {
    "Welcome to the career path": {
        "Getting started": {
            "Welcome to the Frontend Path": "3.04",
            "Let's Make a Cake!": "5:48",
            "The Scrimba Community": "3:12",
        },
        "Your own personalized web app": {
            "Add your Name and Emoji": "2:41",
            "Display Photos": "2:16",
            "Change the Background Image": "1:19",
            "Choose a Color": "1:03",
            "Set the Font, Border, and Column Count": "2:25",
            "Share your website": "1:35",
        }
    },
    "Web dev basics" : {
        "Build & deploy your first website": {
            "Module 2 intro - web dev basics": "2.11",
            "HTML tags": "3:18",
            "Write a news article!": "2:06",
            "Aside: Proper HTML heading structure": "1:03",
            "The <img> tag": "4:56",
            "Nesting": "2:49",
            "Internet superpowers -> Change the BBC news!": "4:57",
            "Buttons": "1:59",
            "Input Tags": "4:58",
            "Let's build Google!": "3:50",
            "Anchor tags": "4:33",
            "Add an anchor tag to Google.com": "1:35",
            "Proper document structure": "3:22",
            "Lists": "3:54",
            "Aside: Description lists": "3:22",
            "Build a Personal Website": "8:42",
            "A quick intro into Web Standards": "1:39",
            "The basics of Semantic HTML": "6:50",
            "Recap": "1:52",
            "Get to know the Modules Channels!": "1:25",
        },
        "Build a Google.com clone": {
            "Let's learn CSS!": "0:44",
            "Write your first lines of CSS!": "4:16",
            "Write your first lines of CSS! - Solution": "3:10",
            "Let's destroy wikipedia": "1:55",
            "Link to the CSS file": "2:36",
            "Set the width of the elements": "2:05",
            "inline vs block elements": "2:15",
            "Margin top": "1:13",
            "Divs rule the world": "2:02",
            "CSS classes": "3:53",
            "Learn margins via flags": "5:54",
            "Add space between our elements": "1:03",
            "Centering with margins": "3:23",
            "Centering our content": "1:19",
            "Padding": "5:17",
            "Border and border-radius": "5:06",
            "Aside challenge: style Twitter button": "4:59",
            "Fix the input field": "4:43",
            "Center the button": "2:16",
            "Style the button": "4:26",
            "Why we can't have two block-level buttons": "4:25",
            "Flexbox": "3:40",
            "Centering both buttons with flexbox": "2:52",
            "Google clone recap": "2:04",
        },
        "Building a digital Business Card" : {
            "Building your digital business card": "0:29",
            "Fix the image path": "2:53",
            "More on Relative Paths": "6:57",
            "Add alt attributore": "4:24",
            "Make image smaller": "1:13",
            "Add a border and padding": "3:46",
            "Flexbox child containers": "3:37",
            "Flex item containers": "1:37",
            "Add a utility class": "3:09",
            "Justify the items": "2:06",
            "Center the card": "1:56",
            "Aside: inheritance (Updated)": "5:23",
            "Center the text via inheritance": "2:57",
            "Add colors": "3:21",
            "Web-safe fonts": "5:05",
            "Margin/padding shorthand": "3:59",
            "Use the margin & padding shorthands": "1:13",
            "Make it your own!": "3:01",
            "Deploy your Digital Business Card": "4:46",
            "Git & Github Intro": "5:48",
            "Business Card recap": "2:09"
        },
        "Build a Space Exploration Site": {
            "Let's go to space!": "0:34",
            "Add a background image form unsplash": "3:57",
            "Center elements and style button": "3:15",
            "Google Fonts": "4:18",
            "@font-face": "2:03",
            "Aside: @font-face performance and usability": "1:42",
            "Aside: spans": "3:56",
            "Add an underline using a span": "1:46",
            "Use an ID for the logo": "4:22",
            "Replace the jpg with a webp": "2:31",
            "Aside: Replaced elements": "2:08",
            "Choose a color pallette from an image": "2:51",
            "Add the terms & conditions section": "3:55",
            "Aside: text shadow": "5:57",
            "Improving the readability with text shadows": "1:57",
            "HTML lang attribute": "1:38",
            "Space Exploration recap": "1:41",
        },
        "Build a Birthday GIFt site": {
            "Let's build a Birthday GIFt site!": "1:07",
            "Add basic header styling": "3:31",
            "Set the colors": "1:22",
            "Add shadow on text": "3:17",
            "We have a problem that flexbox can fix": "2:32",
            "Align-items": "5:59",
            "Flex-direction": "4:25",
            "Turn the header into a flexbox": "1:41",
            "Fix date and age design": "4:06",
            "Create the first gift": "5:17",
            "Replace the img with a div": "4:15",
            "Aside: make elements change on hover (Updated)": "4:06",
            "Add the hover effect": "2:05",
            "Create the next GIFt": "4:19",
            "Create two more GIFts": "2:33",
            "Create the final GIFt": "3:20",
            "ARIA roles and attributes for background images": "4:41",
            "Add the footer": "3:37",
            "Add a background gradient": "3:25",
            "The em and strong tags": "4:05",
            "Intro to audio and video part 1": "4:39",
            "Intro into audio and video part 2": "3:07",
            "Intro into audio and video part 3 (updated)": "4:22",
            "HTML tables": "9:02",
            "Personalize, deploy and share to Discord": "1:36",
            "GIFt site recap": "1:26",
        },
        "Solo Project: Hometown Homepage": {
            "It's time to go solo!": "2:15",
            "Solo Project: Hometown Homepage": "4:04",
            "Get a code review!": "2:46",
            "Congratulations on completing Module 2!": "0:55",
        }
    },
    "Making Websites interactive": {
        "Build a passenger counter app": {
            "Making Websites Interactive - Module Intro": "1:39",
            "Share your plan in #today-i-will!": "0:35",
            "Let's build a passenger counter app!": "0:59",
            "Setting up our JavaScript file": "2:59",
            "Write your first JavaScript variable": "4:52",
            "Basic mathematical operations": "3:35",
            "Reassigning and incrementing": "3:46",
            "Adding a button": "1:31",
            "The onclick event listener": "3:23",
            "Using functions to write less code": "3:33",
            "Write your first function": "0:43",
            "Write a function that logs the sum": "2:46",
            "Write a function that increments": "1:54",
            "Increment on clicks": "2:08",
            "Display the count": "5:13",
            "The Document Object Model": "1:51",
            "Display the count with innerText": "0:39",
            "Create the save button": "2:05",
            "What is a string?": "1:33",
            "Write your first string variable": "3:39",
            "Log a greeting to the console": "1:16",
            "String vs. Numbers": "2:43",
            "Escape!": "3:11",
            "Render a welcome message": "2:00",
            "Improve the message with string concatenation": "2:15",
            "Use plus equal for count": "0:25",
            "Create the save feature": "4:36",
            "Debugging online": "3:49",
            "Set the count to 0": "2:52",
            "Personalize and Download Your App": "4:37",
            "Deploy with Netlify": "4:02",
            "Congrats & recap": "3:14",
            "Share your win!": "0:27",
        },
        "JavaScript challenges - part 1": {
            "Variables practice": "1:52",
            "Concatenate two strings in a function": "0:58",
            "Incrementing and decrementing": "2:11",
            "Strings and numbers": "1:34",
            "Rendering an error message": "3:15",
            "Calculator challenge": "5:30",
            "Arithmetic Operator Precedence": "4:38",
            "Figma tutorial": "1:04",
            "Solo Project (PRO) - Basketball Scoreboard": "4:21",
            "Build exclusive Solo Projects": "1:32",
        },
        "Set Up a Local Dev Environment": {
            "Section Intro": "2:49",
            "Getting Started with GitHub Desktop": "4:18",
            "Edit with VS Code wand Push to GitHub": "3:45",
            "Deploy and Share Your Solo Project": "1:34",
        },
    }
} 