export const modulesObj = {
    "Welcome to the career path": {
        "Getting started": {
            "Welcome to the Frontend Path": "3:04",
            "Let's Make a Cake!": "5:48",
            "The Scrimba Community": "3:12",
        },
        "Your own personalized web app": {
            "Add your Name and Emoji": "2:41",
            "Display Photos": "2:16",
            "Change the Background Image": "1:19",
            "Choose a Color": "1:03",
            "Set the Font, Border, and Column Count": "2:25",
            "Share your website": "1:35",
        }
    },
    "Web dev basics" : {
        "Build & deploy your first website": {
            "Module 2 intro - web dev basics": "2:11",
            "HTML tags": "3:18",
            "Write a news article!": "2:06",
            "Aside: Proper HTML heading structure": "1:03",
            "The img tag": "4:56",
            "Nesting": "2:49",
            "Internet superpowers -> Change the BBC news!": "4:57",
            "Buttons": "1:59",
            "Input Tags": "4:58",
            "Let's build Google!": "3:50",
            "Anchor tags": "4:33",
            "Add an anchor tag to Google.com": "1:35",
            "Proper document structure": "3:22",
            "Lists": "3:54",
            "Aside: Description lists": "3:22",
            "Build a Personal Website": "8:42",
            "A quick intro into Web Standards": "1:39",
            "The basics of Semantic HTML": "6:50",
            "Recap": "1:52",
            "Get to know the Modules Channels!": "1:25",
        },
        "Build a Google.com clone": {
            "Let's learn CSS!": "0:44",
            "Write your first lines of CSS!": "4:16",
            "Write your first lines of CSS! - Solution": "3:10",
            "Let's destroy wikipedia": "1:55",
            "Link to the CSS file": "2:36",
            "Set the width of the elements": "2:05",
            "inline vs block elements": "2:15",
            "Margin top": "1:13",
            "Divs rule the world": "2:02",
            "CSS classes": "3:53",
            "Learn margins via flags": "5:54",
            "Add space between our elements": "1:03",
            "Centering with margins": "3:23",
            "Centering our content": "1:19",
            "Padding": "5:17",
            "Border and border-radius": "5:06",
            "Aside challenge: style Twitter button": "4:59",
            "Fix the input field": "4:43",
            "Center the button": "2:16",
            "Style the button": "4:26",
            "Why we can't have two block-level buttons": "4:25",
            "Flexbox": "3:40",
            "Centering both buttons with flexbox": "2:52",
            "Google clone recap": "2:04",
        },
        "Building a digital Business Card" : {
            "Building your digital business card": "0:29",
            "Fix the image path": "2:53",
            "More on Relative Paths": "6:57",
            "Add alt attributore": "4:24",
            "Make image smaller": "1:13",
            "Add a border and padding": "3:46",
            "Flexbox child containers": "3:37",
            "Flex item containers": "1:37",
            "Add a utility class": "3:09",
            "Justify the items": "2:06",
            "Center the card": "1:56",
            "Aside: inheritance (Updated)": "5:23",
            "Center the text via inheritance": "2:57",
            "Add colors": "3:21",
            "Web-safe fonts": "5:05",
            "Margin/padding shorthand": "3:59",
            "Use the margin & padding shorthands": "1:13",
            "Make it your own!": "3:01",
            "Deploy your Digital Business Card": "4:46",
            "Git & Github Intro": "5:48",
            "Business Card recap": "2:09"
        },
        "Build a Space Exploration Site": {
            "Let's go to space!": "0:34",
            "Add a background image form unsplash": "3:57",
            "Center elements and style button": "3:15",
            "Google Fonts": "4:18",
            "@font-face": "2:03",
            "Aside: @font-face performance and usability": "1:42",
            "Aside: spans": "3:56",
            "Add an underline using a span": "1:46",
            "Use an ID for the logo": "4:22",
            "Replace the jpg with a webp": "2:31",
            "Aside: Replaced elements": "2:08",
            "Choose a color pallette from an image": "2:51",
            "Add the terms & conditions section": "3:55",
            "Aside: text shadow": "5:57",
            "Improving the readability with text shadows": "1:57",
            "HTML lang attribute": "1:38",
            "Space Exploration recap": "1:41",
        },
        "Build a Birthday GIFt site": {
            "Let's build a Birthday GIFt site!": "1:07",
            "Add basic header styling": "3:31",
            "Set the colors": "1:22",
            "Add shadow on text": "3:17",
            "We have a problem that flexbox can fix": "2:32",
            "Align-items": "5:59",
            "Flex-direction": "4:25",
            "Turn the header into a flexbox": "1:41",
            "Fix date and age design": "4:06",
            "Create the first gift": "5:17",
            "Replace the img with a div": "4:15",
            "Aside: make elements change on hover (Updated)": "4:06",
            "Add the hover effect": "2:05",
            "Create the next GIFt": "4:19",
            "Create two more GIFts": "2:33",
            "Create the final GIFt": "3:20",
            "ARIA roles and attributes for background images": "4:41",
            "Add the footer": "3:37",
            "Add a background gradient": "3:25",
            "The em and strong tags": "4:05",
            "Intro to audio and video part 1": "4:39",
            "Intro into audio and video part 2": "3:07",
            "Intro into audio and video part 3 (updated)": "4:22",
            "HTML tables": "9:02",
            "Personalize, deploy and share to Discord": "1:36",
            "GIFt site recap": "1:26",
        },
        "Solo Project: Hometown Homepage": {
            "It's time to go solo!": "2:15",
            "Solo Project: Hometown Homepage": "4:04",
            "Get a code review!": "2:46",
            "Congratulations on completing Module 2!": "0:55",
        }
    },
    "Making Websites interactive": {
        "Build a passenger counter app": {
            "Making Websites Interactive - Module Intro": "1:39",
            "Share your plan in #today-i-will!": "0:35",
            "Let's build a passenger counter app!": "0:59",
            "Setting up our JavaScript file": "2:59",
            "Write your first JavaScript variable": "4:52",
            "Basic mathematical operations": "3:35",
            "Reassigning and incrementing": "3:46",
            "Adding a button": "1:31",
            "The onclick event listener": "3:23",
            "Using functions to write less code": "3:33",
            "Write your first function": "0:43",
            "Write a function that logs the sum": "2:46",
            "Write a function that increments": "1:54",
            "Increment on clicks": "2:08",
            "Display the count": "5:13",
            "The Document Object Model": "1:51",
            "Display the count with innerText": "0:39",
            "Create the save button": "2:05",
            "What is a string?": "1:33",
            "Write your first string variable": "3:39",
            "Log a greeting to the console": "1:16",
            "String vs. Numbers": "2:43",
            "Escape!": "3:11",
            "Render a welcome message": "2:00",
            "Improve the message with string concatenation": "2:15",
            "Use plus equal for count": "0:25",
            "Create the save feature": "4:36",
            "Debugging online": "3:49",
            "Set the count to 0": "2:52",
            "Personalize and Download Your App": "4:37",
            "Deploy with Netlify": "4:02",
            "Congrats & recap": "3:14",
            "Share your win!": "0:27",
        },
        "JavaScript challenges - part 1": {
            "Variables practice": "1:52",
            "Concatenate two strings in a function": "0:58",
            "Incrementing and decrementing": "2:11",
            "Strings and numbers": "1:34",
            "Rendering an error message": "3:15",
            "Calculator challenge": "5:30",
            "Arithmetic Operator Precedence": "4:38",
            "Figma tutorial": "1:04",
            "Solo Project (PRO) - Basketball Scoreboard": "4:21",
            "Build exclusive Solo Projects": "1:32",
        },
        "Set Up a Local Dev Environment": {
            "Section Intro": "2:49",
            "Getting Started with GitHub Desktop": "4:18",
            "Edit with VS Code wand Push to GitHub": "3:45",
            "Deploy and Share Your Solo Project": "1:34",
        },
        "Build a Blackjack game": {
            "Let's build a Blackjack game!": "0:57",
            "Add the firstCard, and sum": "0:52",
            "if...else conditionals": "5:39",
            "if/else...if/else statement": "3:21",
            "The if...else statement for our game": "1:59",
            "Aside: Booleans": "3:46",
            "Add the hasBlackJack variable": "2:03",
            "Add the isAlive variable": "1:44",
            "Let's practice boolean conditions": "3:25",
            "Add the message variable": "3:21",
            "Link to stylesheet": "2:32",
            "Add basic styling": "4:18",
            "Make the start button work": "5:49",
            "Display the message": "2:32",
            "Display the sum": "5:43",
            "Display the cards": "1:53",
            "New card button": "3:39",
            "Add tto the sum when newCard is clicked": "3:16",
            "Rename the startGame function": "2:11",
            "Solving our cards problem with an array": "3:16",
            "Aside: Intro to arrays": "5:24",
            "Asside: Array indexes": "4:03",
            "Arrays with multiple dta types": "2:18",
            "Aside: Array.push() and .pop()": "4:20",
            "Creating the cards array": "1:04",
            "Push a new card to the array": "1:18",
            "Aside: Loops": "4:01",
            "Write your first loop": "3:22",
            "Aside: For loops and arrays": "3:43",
            "Write your first array-based for loop": "1:29",
            "For loops, arrays and DOM": "2:55",
            "Use a loop to render cards": "2:16",
            "How can we avoid to card-code card values?": "1:31",
            "Aside: Returning values in functions": "4:59",
            "Use a function to set the card values": "3:06",
            "Aside: Math.random()": "4:15",
            "Math.random() * 6": "1:43",
            "Flooring the number with Math.floor()": "1:24",
            "Using Math.random() and Math.floor() to create a dice": "1:40",
            "Completing our dice function": "2:37",
            "Make getRandomCard() work": "2:54",
            "Complete getRandomNumber function": "3:02",
            "Assign values in the startGame function": "2:42",
            "Our new card feature is broken": "0:59",
            "Aside: The AND operator (&&)": "3:41",
            "Write your first logical opperator": "2:04",
            "Aside: The OR operator (||)": "3:02",
            "Only trigger newCard() if you're allowed to": "1:27",
            "Object sneak peek": "4:32",
            "Aside: Intro to objects": "4:43",
            "Create your first object": "3:15",
            "Use an object to store player data": "2:37",
            "Methods on object": "1:58",
            "AI for Coding Students": "7:13",
            "Congrats & recap": "4:24",
        },
        "JavaScript challenges - part 2": {
            "Objects and functions": "2:00",
            "if else": "2:48",
            "Loops and arrays": "2:04",
            "Push, pop, unshift, shift challenge": "3:25",
            "Logical operators": "1:56",
            "Rock papers scissors": "2:59",
            "EmojiFighter": "4:32",
            "Sorting fruits": "2:57",
            "Solo Project (PRO) - Password Generator": "2:43",
        },
        "Build a Chrome Extention": {
            "Let's build a Chrome Extention!": "4:33",
            "Add button and input tag": "1:33",
            "Style the button and input tag": "7:16",
            "Make the input button work with onclick": "1:17",
            "Refactor to addEventListener()": "2:18",
            "Write your first addEventListener()": "1:44",
            "Your turn to refactor": "1:22",
            "Create the myLeads array and inputEl": "2:21",
            "When to use let and const": "3:17",
            "Push to the myLeads Array": "1:10",
            "Push the value form the input field": "2:27",
            "Use a for loop to log out leads": "1:39",
            "Create the unordered list": "1:55",
            "Render the leads in the unordered list": "3:41",
            "How to render li elements with innerHTML": "1:33",
            "Write your first innerHTML": "1:31",
            "More innerHTML practice": "1:48",
            "Render the li elements with innerHTML": "1:07",
            "Use createElement() and append() instead of innerHTML": "3:35",
            "Improving the performance of our app": "3:17",
            "Create the render function": "2:00",
            "Clear the input field": "2:03",
            "Aside: another way to render leads": "2:49",
            "Add the a tag": "4:28",
            "Template strings": "2:30",
            "Write your first template string": "1:15",
            "Make the tempalte string even more dynamic": "0:51",
            "Template strings on multiple lines": "2:53",
            "Refactor the app to use a template string": "1:12",
            "Aside: Convert strings to numbers with Number()": "3:42",
            "Style the list": "3:50",
            "Preparing the deployment": "4:52",
            "Deploying the Chrome Extention": "2:28",
            "What is localStorage?": "3:02",
            "Your first localStorage": "3:48",
            "Storing arrays in localStorage": "6:23",
            "Save the leads to localStorage": "2:28",
            "Get the leads from localStorage": "3:50",
            "Truthy and falsy values": "7:54",
            "Guess the expression - truthy or falsy?": "2:22",
            "Checking lcoalStorage before rendering": "3:37",
            "Style the delete button": "3:17",
            "Make the delete button work": "4:16",
            "How function parameters can improve our code": "5:54",
            "Write your first function parameter": "3:27",
            "Functions with multiple parameters": "3:11",
            "Numbers as function parameters": "1:41",
            "Aside: Arguments vs Parameters": "3:22",
            "Arrays as parameters": "1:54",
            "Refacter renderLeads() to use a parameter": "1:39",
            "Create the tabBtn": "3:19",
            "Save the tab url": "2:35",
            "How to get the current tab?": "4:19",
            "Use the Chrome API to get the tab": "6:18",
            "Deploy the final version": "2:14",
            "Congrats & recap": "5:43",
            "Share your pet!": "1:23",
        },
        "JavaScript challenges - part 3": {
            "let & const": "3:12",
            "Log out items in an array": "1:17",
            "save to localStorage": "1:53",
            "addEventListener and object in array": "2:39",
            "Generate sentence": "4:53",
            "Render images": "6:05",
            "Rounding numbers": "1:45",
            "Convert string to number challenge": "2:24",
            "Solo Project (PRO) - Unit converter": "1:54",
        },
        "Build a Mobile App": {
            "Let's Build a Mobile App!": "1:37",
            "Create new Firebase Project": "5:47",
            "Create new Firebase Realtime Database": "2:57",
            "Set up Database Environment Variable": "1:51",
            "Delete uneeeded code": "3:35",
            "Aside: Push data to Firebase Realtime Database": "3:47",
            "Push a lead to Firebase Realtime Database": "3:22",
            "Aside: Get a snapshot of data using onValue": "4:00",
            "Console lot data inside of onValue": "1:56",
            "Aside: Turn an Object into an Array": "1:35",
            "Render all items using onValue": "2:51",
            "Aside: Delete all data using remove": "4:39",
            "Delete all leads using remove": "3:45",
            "Add label, placeholder and max-width": "2:09",
            "Aside: setting the viewport": "1:32",

            "Adding viewport with meta tag": "1:07",
            "Aside: Favicon": "5:59",
            "Adding favicon and phone icons": "1:26",
            "Aside: Web Application Manifest": "2:39",
            "Turning the web app into 'mobile' app": "1:33",
            "Deploy to Netlify": "2:27",
            "Add app to home screen": "1:35",
            "Recap": "3:27",
        },
    },
    "Accessible development": {
        "Accessible Development" : {
            "Let's learn to make the web accessible": "1:06",
            "Understanding web accessibility": "4:49",
            "Aside: Text contrast": "3:49",
            "Aside: Use of color": "1:18",
            "Text contrast": "6:31",
            "Aside: Alternative text": "5:33",
            "Aside: Links": "7:19",
            "Links and alternative text": "5:07",
            "Aside: Labels": "6:12",
            "Aside: Radio buttons": "1:52",
            "Labels": "3:09",
            "Semantic HTML": "5:45",
            "Lists": "4:42",
            "Text-size": "3:21",
            "Headings": "2:51",
            "ARIA": "5:13",
            "ARIA live regions": "5:50",
            "Aside: Accessible JavaScript": "3:20",
            "Aside: Hiding content": "2:36",
            "Aside: Skip Navigation Link Part 1": "3:31",
            "Aside: SKip Navigation Link Part 2": "2:00",
            "Skip Navigation Link": "1:43",
            "Final challenge part 1": "2:38",
            "Final challenge part 2": "4:12",
            "Outro": "1:13",
        }
    },
    "Essential CSS Concepts": {
        "Build an NFT Site": {
            "Essential CSS Concepts Intro": "1:23",
            "Build an NFT Site Intro": "1:35",
            "Semantic HTML - Header, Main, Section, Footer": "5:41",
            "Set up the CSS basics": "3:58",
            "Aside: Margins - A strange behaviour": "5:39",
            "Header": "3:44",
            "The first section - image": "2:37",
            "The first section - text": "5:49",
            "Aside: Hover and active states (old)": "10:17",
            "The first section - links": "2:21",
            "Aside: background full width": "5:46",
            "Content Container": "3:41",
            "CSS organization new": "3:16",
            "The second section colors": "2:54",
            "A quick word about Flexbox": "0:50",
            "The second section imgs": "4:24",
            "Style the Footer": "2:10",
            "Grouping Selectors": "4:25",
            "Warning: Viewing Problems": "0:44",
            "Aside: Specificity": "6:20",
            "Aside: Compound selectors": "6:19",
            "Aside: Compound selectors and specificity": "4:51",
            "Line-height debug": "3:19",
            "CSS specificity and !important keyword": "2:53",
            "Aside: Buttons/Links": "3:21",
            "Style the buttons individually new": "5:58",
            "Aside: Inline-block": "3:34",
            "space out the buttons": "2:34",
            "Aside: A main class and modifier class": "4:05",
            "Refactor the buttons": "3:17",
            "Aside: Flexbox flex-wrap": "1:18",
            "Aside: Overflow": "6:22",
            "Aside: CSS float": "5:21",
        },
        "CSS Fundamentals: Challenges": {
            "CSS Fundamentals: Challenges | Introduction": "1:00",
            "CSS Fundamentals: Challenge #1 - Setting up the layout": "1:01",
            "CSS Fundamentals: Solution #1 - Setting up the layout": "3:17",
            "CSS Fundamentals: Challenge #2 - Google fonts": "0:46",
            "CSS Fundamentals: Solution #2 - Google fonts": "1:40",
            "CSS Fundamentals: Challenge #3 - Setting up the typography": "1:20",
            "CSS Fundamentals: Solution #3 - Setting up the typography": "2:59",
            "CSS Fundamentals: Challenge #4 - Making things a little more fancy": "2:11",
            "CSS Fundamentals: Solution #4 - Making things a little more fancy": "7:43",
            "CSS Fundamentals: Challenge #5 - Breathing Room": "1:41",
            "CSS Fundamentals: Solution #5 - Breathing Room": "6:34",
            "CSS Fundamentals: Challenge #6 - Playing with colors": "1:07",
            "CSS Fundamentals: Solution #6 - Playing with colors": "3:05",
            "CSS Fundamentals: Challenge #7 - The finer details": "1:21",
            "CSS Fundamentals: Solution #7 - The finer details": "5:08",
            "CSS Fundamentals: Challenge #8 - Creating buttons": "2:57",
            "CSS Fundamentals: Solution #8 - Creating buttons": "5:32",
            "CSS Fundamentals: Challenge #9 - Fancier headings": "0:50",
            "CSS Fundamentals: Solution #9 - Fancier headings": "5:26",
            "CSS Fundamentals: Challenge #10 - Working with what you have": "2:28",
            "CSS Fundamentals: Solution #10 - Working with what you have": "5:01",
            "CSS Fundamentals: Solo Project - Oldagram": "3:39",
        },
        "Building a Coworking Space Site": {
            "Intro": "2:44",
            "Build the foundations": "9:43",
            "Aside: margin: auto on flexbox children": "9:23",
            "Position the menu icon": "2:01",
            "Aside: Position: relative & absolute": "9:26",
            "Add the image banner": "4:46",
            "Add buttons": "6:23",
            "Stop the vertical stretch on the button": "3:07",
            "Aside: Position Fixed": "5:38",
            "Add the chatbox": "5:14",
            "Aside: z-index": "6:04",
            "z-index challenge": "2:23",
            "Outro": "1:38",
            "You've completed Module 4. Well done!": "1:41",
        },
    },
    "Essensial JavaScript concepts": {
        "The World's Most Annoying Cookie" : {
            "Module 5 Intro": "1:52",
            "Cookie Consent Intro": "3:08",
            "Position the modal": "2:40",
            "Aside: setTimeout": "4:29",
            "Set the timer": "1:48",
            "Aside: element.style": "6:16",
            "Make the modal reapper": "2:11",
            "Close the modal": "2:33",
            "Aside: Forms": "7:16",
            "Add a form 1": "2:29",
            "Aside: Forms - submitting": "4:56",
            "Aside: Forms - challenge": "2:32",
            "Aside: Validation Attributes": "7:42",
            "Submit the form": "3:13",
            "Aside: preventDefault": "4:15",
            "preventDefault Challenge": "3:05",
            "Buttons in forms - weird behavior": "2:33",
            "Add modal message": "2:29",
            "Add modal messages 2": "5:30",
            "Add modal messages 3": "3:25",
            "Aside: FormData": "3:34",
            "Form Data 1": "2:13",
            "Aside FormData methods": "3:22",
            "Form Data 2": "2:38",
            "Aside: Disabling elements": "6:05",
            "Disable the close button": "3:09",
            "There is no choice 1": "3:30",
            "Aside: classlist.toggle": "4:00",
            "Aside: Classlist Toggle Challenge": "2:30",
            "There is no choice 2": "2:55",
            "Accessibility Issues": "1:50",
            "Recap": "1:30",
        },
        "Pumpkin's Purrfect Meme Picker": {
            "Intro": "3:37",
            "What a horrible for loop": "2:57",
            "Aside: for of": "4:43",
            "Use a for of": "1:42",
            "Nest the for of": "4:44",
            "Render out the emotions 1": "4:09",
            "Render out emotions 2": "5:51",
            "Aside: import the data": "5:57",
            "Import the data": "2:20",
            "Aside: Radio Inputs": "5:39",
            "Render the radio inputs": "5:40",
            "Aside: .includes()": "5:52",
            "remove duplicates": "3:16",
            "Aside: e.target": "5:44",
            "Get the id of the clicked option": "3:19",
            "Aside: parentElement": "3:14",
            "Aside: classlist add/remove": "6:47",
            "Add colour to the selected emotion": "5:50",
            "Aside: gatElementsByClassName": "4:58",
            "Remove the highlight class": "2:18",
            "Aside: querySelector and why it's useful": "4:33",
            "Connect the buton": "4:46",
            "Has an emotion been chosen?": "3:14",
            "Aside: checkbox": "5:32",
            "isGif": "3:45",
            "Aside: filter()": "6:13",
            "Aside: filter() 2": "4:51",
            "Find matches with .filter()": "4:17",
            "Animated GIFs Only": "5:55",
            "Introducting two important functions": "4:34",
            "If there's only one cat...": "4:26",
            "If there's more than one cat...": "4:03",
            "renderCat()": "5:17",
            "Close the modal": "2:02",
            "The order of things": "2:44",
            "Aside: Select Element": "6:40",
            "Recap": "2:58",
            "Get expert feedback on your JavaScript and build exclusive projects": "1:37",
        },
        "Twimba: Twitter Clone": {
            "Intro": "4:44",
            "Import the data": "3:36",
            "Aside: TextArea": "3:29",
            "Add TextArea": "4:04",
            "Tweet Boilerplate": "3:22",
            "Tweet Boilerplate Challenge": "4:20",
            "Aside: forEach()": "5:20",
            "Use forEach to build the html": "1:41",
            "Render the tweets to the feed": "3:58",
            "Aside: CDN Font Awesome": "6:05",
            "Add some awesome icons": "4:37",
            "Like a tweet part 1: explanation": "1:58",
            "Aside: Data attributes new": "3:30",
            "Aside: Data Attr JS and Challenge": "6:07",
            "Aside: Data Attribute Naming Issues": "3:10",
            "Like a tweet part 2: data attributes": "2:20",
            "Like a tweet part 3: eventListener": "5:11",
            "Like a tweet part 4 handleLikeClick()": "4:05",
            "Like a tweet part 5: find the tweet object": "6:20",
            "Aside: Copying objects and arrays": "3:33",
            "Like a tweet part 6: render the increment": "1:05",
            "Unline a tweet": "3:11",
            "Flip a boolean": "2:01",
            "Retweet a tweet": "8:07",
            "Aside: Conditionally render CSS class": "6:53",
            "Color the icons": "6:01",
            "Replies 1: get UUIDs of tweets with replies": "2:55",
            "Replies 2: HTML string for replies and add to parent div": "4:42",
            "Replies 3: toggle hidden": "4:49",
            "Refactor the tweet btn": "4:23",
            "Aside UUID": "6:46",
            "Build the new Tweet object": "3:46",
            "Render a new tweet": "2:21",
            "UX Fixes": "5:01",
            "Recap": "3:21",
            "Deploy Twimba": "1:08",
        },
        "Essential JS Mini Projects": {
            "Intro to Mini Projects": "1:14",
            "Object Destructuring": "3:12",
            "Object Destructuring Challange": "2:02",
            "The .map() Method": "6:37",
            "The .map() Method Challenge": "3:59",
            "The .join() Method": "2:49",
            "The .join() Method Challenge": "2:18",
            ".map() vs. forEach()": "4:45",
            "For loop Break and Continue": "5:14",
            "The dangers of innerHTML": "5:26",
            "Beyond Funciton Declarations 1: Funciton Expressions": "3:18",
            "Beyond Function Declarations 2: Function Expression Challenge": "1:52",
            "Beyond Function Declarations 3: Arrow Functions": "5:44",
            "Aside: Arrow functions challenge": "4:00",
            "Aside: inline arrow function challenge": "2:34",
            "Import Export (named)": "4:21",
            "Import Export (default)": "3:57",
            "Aside: array.reduce()": "6:06",
            "Aside .reduce() challenge": "2:28",
            "The .reduce() Method with objects": "7:35",
            "The .reduce() Method with Objects Challenge": "3:29",
            "Default Parameters": "2:56",
            "Super Challenge Set-up": "3:21",
            "Super Challenge Solution": "8:49",
            "The ternary Operator": "4:01",
            "The Ternary Operator for Complex Conditionals": "3:05",
            "Ternary Operator Challenge": "3:47",
            "Twimba Ternary Refactor": "4:50",
            "The Rest Parameter": "5:23",
            "The Rest Parameter Challenge": "6:42",
            "Spread Syntax (...)": "4:11",
            "Spread Syntax (...) Challenge": "5:16",
            "Short-circuiting with OR (||)": "5:02",
            "Short-circuiting with OR (||) Challenge": "2:14",
            "Short-circuiting with AND (&&)": "2:47",
            "Short-circuiting with AND (&&) Challenge": "4:01",
            "Switch Statements (new)": "5:32",
            "Constructors: Date()": "5:27",
            "The Error() Constructor": "3:22",
            "Objects with Methods and 'this'": "5:14",
            "Objects to Constructor Functions": "4:36",
            "Constructor Function Challenge": "5:17",
            "Constructor Functions to Classes": "5:28",
            "Constructor Functions to Classes Challenge": "2:07",
            "Debugging: Errors": "7:16",
            "Debugging: try...catch": "4:39",
            "Recap": "2:08",
            "Solo Project - Restaurant Ordering app": "4:02",
            "Deploy your Solo Project": "0:44",
            "Congratulations on completing modules 5!": "1:30",
        }
    }
} 